In [18]:
import pandas as pd

# Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# load the dataset
df_charging = pd.read_csv('/content/drive/MyDrive/DS 3000/ev_charging_patterns.csv')
df_charging.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,User ID,Vehicle Model,Battery Capacity (kWh),Charging Station ID,Charging Station Location,Charging Start Time,Charging End Time,Energy Consumed (kWh),Charging Duration (hours),Charging Rate (kW),Charging Cost (USD),Time of Day,Day of Week,State of Charge (Start %),State of Charge (End %),Distance Driven (since last charge) (km),Temperature (°C),Vehicle Age (years),Charger Type,User Type
0,User_1,BMW i3,108.463007,Station_391,Houston,2024-01-01 00:00:00,2024-01-01 00:39:00,60.712346,0.591363,36.389181,13.087717,Evening,Tuesday,29.371576,86.119962,293.602111,27.947953,2.0,DC Fast Charger,Commuter
1,User_2,Hyundai Kona,100.000000,Station_428,San Francisco,2024-01-01 01:00:00,2024-01-01 03:01:00,12.339275,3.133652,30.677735,21.128448,Morning,Monday,10.115778,84.664344,112.112804,14.311026,3.0,Level 1,Casual Driver
2,User_3,Chevy Bolt,75.000000,Station_181,San Francisco,2024-01-01 02:00:00,2024-01-01 04:48:00,19.128876,2.452653,27.513593,35.667270,Morning,Thursday,6.854604,69.917615,71.799253,21.002002,2.0,Level 2,Commuter
3,User_4,Hyundai Kona,50.000000,Station_327,Houston,2024-01-01 03:00:00,2024-01-01 06:42:00,79.457824,1.266431,32.882870,13.036239,Evening,Saturday,83.120003,99.624328,199.577785,38.316313,1.0,Level 1,Long-Distance Traveler
4,User_5,Hyundai Kona,50.000000,Station_108,Los Angeles,2024-01-01 04:00:00,2024-01-01 05:46:00,19.629104,2.019765,10.215712,10.161471,Morning,Saturday,54.258950,63.743786,203.661847,-7.834199,1.0,Level 1,Long-Distance Traveler

In [19]:
# Overview of dataset columns, types, and missing values
df_charging.info()

# Basic statistics for numerical columns
df_charging.describe()

# Count of missing values per column
df_charging.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1320 entries, 0 to 1319
Data columns (total 20 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   User ID                                   1320 non-null   object
 1   Vehicle Model                             1320 non-null   object
 2   Battery Capacity (kWh)                    1320 non-null   float64
 3   Charging Station ID                       1320 non-null   object
 4   Charging Station Location                 1320 non-null   object
 5   Charging Start Time                       1320 non-null   object
 6   Charging End Time                         1320 non-null   object
 7   Energy Consumed (kWh)                     1254 non-null   float64
 8   Charging Duration (hours)                 1320 non-null   float64
 9   Charging Rate (kW)                        1254 non-null   float64
 10  Charging Cost (USD)                       1320 non-null   float64
 11  Time of Day                               1320 non-null   object
 12  Day of Week                               1320 non-null   object
 13  State of Charge (Start %)                 1320 non-null   float64
 14  State of Charge (End %)                   1320 non-null   float64
 15  Distance Driven (since last charge) (km)  1254 non-null   float64
 16  Temperature (°C)                          1320 non-null   float64
 17  Vehicle Age (years)                       1320 non-null   float64
 18  Charger Type                              1320 non-null   object
 19  User Type                                 1320 non-null   object
dtypes: float64(10), object(10)
memory usage: 206.4+ KB

User ID                                      0
Vehicle Model                                0
Battery Capacity (kWh)                       0
Charging Station ID                          0
Charging Station Location                    0
Charging Start Time                          0
Charging End Time                            0
Energy Consumed (kWh)                       66
Charging Duration (hours)                    0
Charging Rate (kW)                          66
Charging Cost (USD)                          0
Time of Day                                  0
Day of Week                                  0
State of Charge (Start %)                    0
State of Charge (End %)                      0
Distance Driven (since last charge) (km)    66
Temperature (°C)                             0
Vehicle Age (years)                          0
Charger Type                                 0
User Type                                    0
dtype: int64

In [20]:
# Filling errors/missing values in data-set
# Fill tiny missing 'Energy Consumed (kWh)' with median
df_charging['Energy Consumed (kWh)'].fillna(df_charging['Energy Consumed (kWh)'].median(), inplace=True)

# Fill 'Charging Rate (kW)' and 'Distance Driven (since last charge) (km)' with median
df_charging['Charging Rate (kW)'].fillna(df_charging['Charging Rate (kW)'].median(), inplace=True)
df_charging['Distance Driven (since last charge) (km)'].fillna(df_charging['Distance Driven (since last charge) (km)'].median(), inplace=True)

# Verify missing values were handled
df_charging.isnull().sum()

/tmp/ipython-input-1827611821.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_charging['Energy Consumed (kWh)'].fillna(df_charging['Energy Consumed (kWh)'].median(), inplace=True)
/tmp/ipython-input-1827611821.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_charging['Charging Rate (kW)'].fillna(df_charging['Charging Rate (kW)'].median(), inplace=True)
/tmp/ipython-input-1827611821.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_charging['Distance Driven (since last charge) (km)'].fillna(df_charging['Distance Driven (since last charge) (km)'].median(), inplace=True)

User ID                                     0
Vehicle Model                               0
Battery Capacity (kWh)                      0
Charging Station ID                         0
Charging Station Location                   0
Charging Start Time                         0
Charging End Time                           0
Energy Consumed (kWh)                       0
Charging Duration (hours)                   0
Charging Rate (kW)                          0
Charging Cost (USD)                         0
Time of Day                                 0
Day of Week                                 0
State of Charge (Start %)                   0
State of Charge (End %)                     0
Distance Driven (since last charge) (km)    0
Temperature (°C)                            0
Vehicle Age (years)                         0
Charger Type                                0
User Type                                   0
dtype: int64

In [21]:
#extract categorical variables
categorical_cols = [
    'Vehicle Model', 'Charging Station Location', 'Time of Day',
    'Day of Week', 'Charger Type', 'User Type'
]

#drop ID columns
drop_cols = ['User ID', 'Charging Station ID']
df_charging.drop(columns=drop_cols, inplace=True, errors='ignore')

# One-hot encode categorical variables
df_encoded = pd.get_dummies(df_charging, columns=categorical_cols, drop_first=True)

df_encoded.head()

,Battery Capacity (kWh),Charging Start Time,Charging End Time,Energy Consumed (kWh),Charging Duration (hours),Charging Rate (kW),Charging Cost (USD),State of Charge (Start %),State of Charge (End %),Distance Driven (since last charge) (km),...,Day of Week_Monday,Day of Week_Saturday,Day of Week_Sunday,Day of Week_Thursday,Day of Week_Tuesday,Day of Week_Wednesday,Charger Type_Level 1,Charger Type_Level 2,User Type_Commuter,User Type_Long-Distance Traveler
0,108.463007,2024-01-01 00:00:00,2024-01-01 00:39:00,60.712346,0.591363,36.389181,13.087717,29.371576,86.119962,293.602111,...,False,False,False,False,True,False,False,False,True,False
1,100.000000,2024-01-01 01:00:00,2024-01-01 03:01:00,12.339275,3.133652,30.677735,21.128448,10.115778,84.664344,112.112804,...,True,False,False,False,False,False,True,False,False,False
2,75.000000,2024-01-01 02:00:00,2024-01-01 04:48:00,19.128876,2.452653,27.513593,35.667270,6.854604,69.917615,71.799253,...,False,False,False,True,False,False,False,True,True,False
3,50.000000,2024-01-01 03:00:00,2024-01-01 06:42:00,79.457824,1.266431,32.882870,13.036239,83.120003,99.624328,199.577785,...,False,True,False,False,False,False,True,False,False,True
4,50.000000,2024-01-01 04:00:00,2024-01-01 05:46:00,19.629104,2.019765,10.215712,10.161471,54.258950,63.743786,203.661847,...,False,True,False,False,False,False,True,False,False,True

In [16]:
df_charging['Charging Start Time'] = pd.to_datetime(df_charging['Charging Start Time'])
df_charging['Charging End Time'] = pd.to_datetime(df_charging['Charging End Time'])

# Extract hour of day and weekday as features
df_encoded['start_hour'] = df_charging['Charging Start Time'].dt.hour
df_encoded['start_weekday'] = df_charging['Charging Start Time'].dt.weekday

# Drop original datetime columns if desired
df_encoded.drop(columns=['Charging Start Time', 'Charging End Time'], inplace=True)

In [22]:
# Export and Share
# Goal:
#   - Export dataset into organized folders
#   - Ensure teammates can easily find all project files

import os
os.makedirs('data', exist_ok=True)

# df_encoded should already be created in Block-YY
df_encoded.to_csv('data/charging_data_encoded.csv', index=False)

print("  - data/charging_data_encoded.csv")

  - data/charging_data_encoded.csv